config/routes.rb
Rails.application.routes.draw do

  root to: 'user#confirm_email'
  match '/confirm_email/:token', to: 'user#confirm_email', via: 'get'
  match '/new', to: 'user#new', via: 'get'
  match '/index', to: 'user#index', via: 'get'
  match '/create', to: 'user#create', via: 'post'
  match '/bounce', to: 'hook#bounce', via: 'post'
  match '/complaint', to: 'hook#complaint', via: 'post'
  match '/unsubscribe', to: 'hook#unsubscribe', via: 'post'
  match '/click', to: 'hook#click', via: 'post'

end

app/models/user.rb
class User < ActiveRecord::Base

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX } , uniqueness: { case_sensitive:false }
  before_create :generate_token

  def email_activate
    self.email_confirmed = true
    self.confirm_token = nil
    save!(:validate => false)
  end

  private
  def generate_token
    if self.confirmation_token.blank?
      self.confirmation_token = SecureRandom.urlsafe_base64.to_s
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hook_controller.rb
class HookController < ApplicationController

  require 'csv'

  skip_before_filter  :verify_authenticity_token
  before_filter :verify_mailgun

  def bounce
    CsvWrite.write_csv(params[:recipient], params[:ip], params[:subject], params[:type])
    user = User.where(:email => params[:recipient])
    user.update_attribute(:valid_email => false) if user.present?
    render nothing: true
  end

  def unsubscribe
    # p params[:recipient]
    user = User.where(:email => params[:recipient])
    user.update_attribute(:valid_email => false) if user.present?
    render nothing: true
  end

  def complaint
    # p params[:recipient]
    user = User.where(:email => params[:recipient])
    user.update_attribute(:valid_email => false) if user.present?
    render nothing: true
  end

  def click
    CsvWrite.write_csv(params[:recipient], params[:ip], params[:subject], params[:type])
    render nothing: true
  end

  private
  def verify_mailgun
    result = MailgunWebhook.verify_authenticity(ENV['mailgun-api-key'], params[:token], params[:timestamp], params[:signature])
    unless !result
      return false
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @users = User.all
    @confirmed_users = @users.where(:confirmation_token => nil)
    @unconfirmed_users = @users.where('confirmation_token is not ?', nil)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if MailgunWebhook.is_valid_email(@user.email) && @user.save
      @user.update_attribute(:valid_email => true)
      MailgunTask.activation_email(@user.id)
      flash[:success] = "Please confirm your email address to continue"
    else
      flash[:error] = "Ooooppss, something went wrong!"
    end
    render 'new'
  end

  def confirm_email
    user = User.find_by_confirmation_token(params[:confirmation_token])
    if user
      user.email_activate
      flash[:success] = "Welcome, Your email has been confirmed."
    end
    # redirect_to root_url
  end

  private
  def user_params
		params.require(:user).permit(:email)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hook_helper.rb
module HookHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/hook/bounce.html.erb
<h1>Hook#bounce</h1>
<p>Find me in app/views/hook/bounce.html.erb</p>

app/views/hook/complaint.html.erb
<h1>Hook#complaint</h1>
<p>Find me in app/views/hook/complaint.html.erb</p>

app/views/hook/unsubscribe.html.erb
<h1>Hook#unsubscribe</h1>
<p>Find me in app/views/hook/unsubscribe.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudySoupAssign</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="flash">
    <% flash.each do |key, value| %>
    		<div class="alert alert-<%= key %>">
    			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    			<%= value %>
    		</div>
  	<% end %>
  </div>
  <div class="container" style="margin:100px;">
    <%= yield %>
  </div>

</body>
</html>

app/views/user/confirm_email.html.erb
<div class="row" style="text-align:center;">
  <h1><p>Thank you for activating your account</p></h1>
</div>

app/views/user/index.html.erb
<div class="row">
  <div class="offset-md-3 col-md-3">Number of confirmed users is </div>
  <div class="col-md-2">: <%= @confirmed_users.count %></div>
</div>
<div class="row">
  <div class="col-md-3 offset-md-3">Number of unconfirmed users is </div>
  <div class="col-md-2">: <%= @unconfirmed_users.count %></div>
</div>

app/views/user/new.html.erb
<%= form_for @user, :url => create_path, :method => :post do |f| %>
  <div class="form-group">
    <div class="row">
      <%= f.label :email, 'Email', class: 'control-label col-md-1' %>
  		<div class="col-md-6">
  			<%= f.text_field :email, :placeholder => 'Email', :class => 'form-control' %>
  		</div>
      <%= submit_tag "Send Invite", class: "col-md-2 btn btn-primary" %>
    </div>
  </div>
<% end %>